MonsterSid.translates = {
    PolicyTitle: 'Polityka plików cookies',
    PolicyDesc: 'Korzystamy z plików cookies, aby ułatwić Ci korzystanie z naszej strony. Zostając na stronie zgadzasz się na użycie plików cookie.',
    PolicyAccept: 'Akceptuję',
    PolicyMore: 'Więcej informacji',
    DisableTitle: 'Czym sa pliki cookies?',
    DisableBrowser: 'Jak wyłączyć pliki cookies w przeglądarce ${browser}',
    DisableFirefox: 'W menu "Narzędzia" wybierz "Opcje" i w nich zakładkę "Prywatność".<br>Przeglądarka daje Ci możliwość zaznaczenia, że nie chcesz być śledzony w ogóle albo usunięcia pojedynczych ciasteczek poszczególnych witryn.',
    DisableMSIE: 'W menu "Narzędzia" wybierz "Opcje internetowe" i w nich zakładkę "Prywatność".<br>Specjalnym suwakiem możesz regulować ogólny poziom prywatności albo przyciskiem "Witryny" zarządzać ustawieniami poszczególnych serwisów internetowych.',
    DisableChromium: 'W menu ukrytym pod trzema poziomymi kreseczkami w prawym górnym rogu przeglądarki wybierz "Narzędzia" a potem "Wyczyść dane przeglądania...". Oprócz możliwości czyszczenia plików cookie, znajduje się tam link "Więcej informacji", który prowadzi do szczegółowego opisu funkcji prywatności przeglądarki.',
    DisableOpera: 'Przyciskiem "Opera" w lewym górnym rogu otwórz menu i wybierz w nim "Ustawienia" i dalej "Wyczyść historię przeglądania...".<br>Oprócz możliwości skasowania już ustawionych plików cookie, jest tam też przycisk "Zarządzaj ciasteczkami..." prowadzący do bardziej zaawansowanych opcji dla poszczególnych witryn.',
    DisableSafari: 'W menu "Safari" wybierz "Preferencje" i w nich zakładkę "Prywatność". Znajdziesz w niej liczne opcje dotyczące plików cookie.',
    DisableMobile: 'Każdy model telefonu może tę funkcję obsługiwać w inny sposób. Dlatego zachęcamy do zapoznania się z opcjami prywatności w dokumentacji na stronie internetowej producenta Twojego urządzenia mobilnego.',
    DisableDesc: 'Wiele stron internetowych zapisuje na Twoim komputerze, a dokładniej w schowku konkretnej przeglądarki (Firefox, Internet Explorer, Chrome i inne) na Twoim koncie użytkownika komputera lub telefonu, na którym łączysz się z Siecią, tzw. pliki cookie.<br>Zazwyczaj pliki cookie są bardzo pożyteczne. Dzięki nim zapamiętywane są Twoje indywidualne ustawienia i dzięki nim możesz się zalogować do swojej poczty.<br>Autorzy stron internetowych wiedzą dzięki nim, jak wielu użytkowników do nich zagląda i co konkretnie czytają, a co obchodzą z daleka.<br>Informacje zbierane przy użyciu plików cookie mogą też służyć do zbierania informacji o Tobie w celach handlowych. Np. jeżeli często wchodzisz na strony o książkach, będziesz widział więcej reklam księgarni.<br>Na szczęście, jeżeli uważasz, że obecność plików cookie narusza Twoją prywatność, możesz w każdej chwili je wyłączyć albo dla konkretnej witryny albo w ogóle dla wszystkich połączeń z Twojej przeglądarki.',
    DisablePluginTitle: 'Jak automatycznie akceptować pliki cookies?',
    DisablePluginDesc: 'Jeśli zgadzasz się na korzystanie z plików cookies przez strony i nie chcesz za każdym razem akceptować ich politykę na każdej stronie wystarczy, że klikniesz ${pluginLink}, aby zainstalować dodatek do przeglądarki, jeśli posiadasz własną stronę możesz także pobrać kod do umieszczenia podobnego powiadomienia na własnej stronie, które będzie automatycznie wyłaczane i akceptowane jeśli życzą sobie tego użytkownicy',
    DisableClickHere: 'tutaj',
    LanguegeSet: 'Ustawiono język polski',
    CookiesPolicyAccepted: 'Zaakceptowano już politykę cookies',
};
